parameters:
    bigfoot.display_menu.class: 'Bigfoot\Bundle\NavigationBundle\Services\DisplayMenu'
services:
    kernel.listener.bigfoot_navigation_menu_listener:
        class: Bigfoot\Bundle\NavigationBundle\Listener\MenuListener
        tags:
            - { name: kernel.event_listener, event: bigfoot.menu.generate, method: onMenuGenerate }
    form.type.bigfoot_menu:
        class: Bigfoot\Bundle\NavigationBundle\Form\MenuType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: bigfoot_menu }
    form.type.bigfoot_menu_item:
        class: Bigfoot\Bundle\NavigationBundle\Form\ItemType
        arguments: [@bigfoot.route_manager, @doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: bigfoot_menu_item }
    bigfoot.form.type.parameters_collection:
        class: Bigfoot\Bundle\NavigationBundle\Form\Type\ParametersCollectionType
        tags:
            - { name: form.type, alias: parameters_collection }
    bigfoot.display_menu:
        class: '%bigfoot.display_menu.class%'
        arguments: [@service_container]
    form.type.bigfoot_item_parameter:
            class: Bigfoot\Bundle\NavigationBundle\Form\ItemParameterType
            arguments:
                - @doctrine.orm.entity_manager
