services:
    # Menu Item Manager
    bigfoot_navigation.manager.menu_item:
        class: Bigfoot\Bundle\NavigationBundle\Manager\Menu\ItemManager
        arguments:
            - @doctrine.orm.entity_manager
    # Menu Item Url Manager
    bigfoot_navigation.manager.menu_item_url:
        class: Bigfoot\Bundle\NavigationBundle\Manager\Menu\Item\UrlManager
        arguments:
            - @doctrine.orm.entity_manager
            - @router

    # Menu Listener
    bigfoot_navigation.listener.menu:
        class: Bigfoot\Bundle\NavigationBundle\Listener\MenuListener
        arguments: [@security.context]
        tags:
            - { name: kernel.event_subscriber }

    # Menu Type
    bigfoot_navigation.form.type.menu:
        class: Bigfoot\Bundle\NavigationBundle\Form\Type\MenuType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: admin_menu }

    # Menu Item Type
    bigfoot_navigation.form.type.menu_item:
        class: Bigfoot\Bundle\NavigationBundle\Form\Type\Menu\ItemType
        arguments:
            - @doctrine.orm.entity_manager
            - @bigfoot_core.manager.route
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: form.type, alias: admin_menu_item }

    # Menu Item Parameter Type
    bigfoot_navigation.form.type.menu_item_parameter:
        class: Bigfoot\Bundle\NavigationBundle\Form\Type\Menu\Item\ParameterType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: admin_menu_item_parameter }

    # Menu Item Attribute Type
    bigfoot_navigation.form.type.menu_item_attribute:
        class: Bigfoot\Bundle\NavigationBundle\Form\Type\Menu\Item\AttributeType
        tags:
            - { name: form.type, alias: admin_menu_item_attribute }

    # Route Parameter Type
    bigfoot_navigation.form.type.route_parameter:
        class: Bigfoot\Bundle\NavigationBundle\Form\Type\Route\ParameterType
        tags:
            - { name: form.type, alias: admin_route_parameter }
    # Twig extensions
    bigfoot.twig.menu_extension:
        class: Bigfoot\Bundle\NavigationBundle\Twig\MenuExtension
        arguments: [ @bigfoot_navigation.manager.menu_item_url ]
        tags:
            - { name: twig.extension }
